definitions:
  domain.User:
    properties:
      balance:
        type: number
      createdBy:
        type: string
      createdDate:
        type: string
      currency:
        type: string
      id:
        type: string
      isDeleted:
        type: integer
      name:
        type: string
      scale:
        type: integer
      updatedBy:
        type: string
      updatedDate:
        type: string
      version:
        type: integer
    required:
    - balance
    - currency
    - name
    - scale
    type: object
  user.CreateUserRequestDto:
    properties:
      user:
        $ref: '#/definitions/user.UserDto'
    type: object
  user.CreateUserResponseDto:
    properties:
      user:
        $ref: '#/definitions/user.UserDto'
    type: object
  user.DeleteUserRequestDto:
    properties:
      isHardDelete:
        type: boolean
      userId:
        type: string
    required:
    - userId
    type: object
  user.UpdateUserRequestDto:
    properties:
      user:
        $ref: '#/definitions/user.UserDto'
    type: object
  user.UserDto:
    properties:
      balance:
        type: number
      currency:
        type: string
      id:
        type: string
      name:
        type: string
      scale:
        type: integer
    required:
    - balance
    - currency
    - name
    - scale
    type: object
  withdraw.WithdrawRequestDto:
    properties:
      amount:
        type: number
      userId:
        type: string
    required:
    - amount
    - userId
    type: object
info:
  contact: {}
paths:
  /paper-wallet-core-service/users:
    delete:
      consumes:
      - application/json
      description: Delete a user by their ID, either hard or soft delete based on
        the provided flag
      parameters:
      - default: iOS
        description: Channel identifier
        in: header
        name: X-Channel-Id
        required: true
        type: string
      - default: RequestId
        description: Unique request identifier
        in: header
        name: X-Request-Id
        required: true
        type: string
      - default: gateway
        description: Service identifier
        in: header
        name: X-Service-Id
        required: true
        type: string
      - description: Username associated with the request
        in: header
        name: X-Username
        required: true
        type: string
      - default: id
        description: Language preference for the response
        in: header
        name: Accept-Language
        required: true
        type: string
      - default: 'User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_4_2 like Mac OS
          X'
        description: User agent identifier
        in: header
        name: User-Agent
        required: true
        type: string
      - default: Basic dXNlcm5hbWU6cGFzc3dvcmQ=
        description: Authorization token
        in: header
        name: Authorization
        required: true
        type: string
      - default: 1.2.3
        description: Application version
        in: header
        name: X-App-Version
        type: string
      - description: Delete User Request
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.DeleteUserRequestDto'
      produces:
      - application/json
      responses:
        "204":
          description: User successfully deleted
      summary: Delete a user
      tags:
      - user-controller
    get:
      consumes:
      - application/json
      description: Retrieve a list of all users
      parameters:
      - default: iOS
        description: Channel identifier
        in: header
        name: X-Channel-Id
        required: true
        type: string
      - default: RequestId
        description: Unique request identifier
        in: header
        name: X-Request-Id
        required: true
        type: string
      - default: gateway
        description: Service identifier
        in: header
        name: X-Service-Id
        required: true
        type: string
      - description: Username associated with the request
        in: header
        name: X-Username
        required: true
        type: string
      - default: id
        description: Language preference for the response
        in: header
        name: Accept-Language
        required: true
        type: string
      - default: 'User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_4_2 like Mac OS
          X'
        description: User agent identifier
        in: header
        name: User-Agent
        required: true
        type: string
      - default: Basic dXNlcm5hbWU6cGFzc3dvcmQ=
        description: Authorization token
        in: header
        name: Authorization
        required: true
        type: string
      - default: 1.2.3
        description: Application version
        in: header
        name: X-App-Version
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.User'
            type: array
      summary: Get all users
      tags:
      - user-controller
    post:
      consumes:
      - application/json
      description: Create a new user with the provided details
      parameters:
      - default: iOS
        description: Channel identifier
        in: header
        name: X-Channel-Id
        required: true
        type: string
      - default: RequestId
        description: Unique request identifier
        in: header
        name: X-Request-Id
        required: true
        type: string
      - default: gateway
        description: Service identifier
        in: header
        name: X-Service-Id
        required: true
        type: string
      - description: Username associated with the request
        in: header
        name: X-Username
        required: true
        type: string
      - default: id
        description: Language preference for the response
        in: header
        name: Accept-Language
        required: true
        type: string
      - default: 'User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_4_2 like Mac OS
          X'
        description: User agent identifier
        in: header
        name: User-Agent
        required: true
        type: string
      - default: Basic dXNlcm5hbWU6cGFzc3dvcmQ=
        description: Authorization token
        in: header
        name: Authorization
        required: true
        type: string
      - default: 1.2.3
        description: Application version
        in: header
        name: X-App-Version
        type: string
      - description: User Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.CreateUserRequestDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/user.CreateUserResponseDto'
      summary: Create a new user
      tags:
      - user-controller
    put:
      consumes:
      - application/json
      description: Update the details of an existing user based on the provided user
        ID and data
      parameters:
      - default: iOS
        description: Channel identifier
        in: header
        name: X-Channel-Id
        required: true
        type: string
      - default: RequestId
        description: Unique request identifier
        in: header
        name: X-Request-Id
        required: true
        type: string
      - default: gateway
        description: Service identifier
        in: header
        name: X-Service-Id
        required: true
        type: string
      - description: Username associated with the request
        in: header
        name: X-Username
        required: true
        type: string
      - default: id
        description: Language preference for the response
        in: header
        name: Accept-Language
        required: true
        type: string
      - default: 'User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_4_2 like Mac OS
          X'
        description: User agent identifier
        in: header
        name: User-Agent
        required: true
        type: string
      - default: Basic dXNlcm5hbWU6cGFzc3dvcmQ=
        description: Authorization token
        in: header
        name: Authorization
        required: true
        type: string
      - default: 1.2.3
        description: Application version
        in: header
        name: X-App-Version
        type: string
      - description: User Data for Update
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.UpdateUserRequestDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.User'
      summary: Update an existing user
      tags:
      - user-controller
  /paper-wallet-core-service/users/{id}:
    get:
      consumes:
      - application/json
      description: Get details of a user by their ID
      parameters:
      - default: iOS
        description: Channel identifier
        in: header
        name: X-Channel-Id
        required: true
        type: string
      - default: RequestId
        description: Unique request identifier
        in: header
        name: X-Request-Id
        required: true
        type: string
      - default: gateway
        description: Service identifier
        in: header
        name: X-Service-Id
        required: true
        type: string
      - description: Username associated with the request
        in: header
        name: X-Username
        required: true
        type: string
      - default: id
        description: Language preference for the response
        in: header
        name: Accept-Language
        required: true
        type: string
      - default: 'User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_4_2 like Mac OS
          X'
        description: User agent identifier
        in: header
        name: User-Agent
        required: true
        type: string
      - default: Basic dXNlcm5hbWU6cGFzc3dvcmQ=
        description: Authorization token
        in: header
        name: Authorization
        required: true
        type: string
      - default: 1.2.3
        description: Application version
        in: header
        name: X-App-Version
        type: string
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.User'
      summary: Get user by ID
      tags:
      - user-controller
  /paper-wallet-core-service/wallet/withdraw:
    post:
      consumes:
      - application/json
      description: Withdraw funds from the user's wallet
      parameters:
      - default: iOS
        description: Channel identifier
        in: header
        name: X-Channel-Id
        required: true
        type: string
      - default: RequestId
        description: Unique request identifier
        in: header
        name: X-Request-Id
        required: true
        type: string
      - default: gateway
        description: Service identifier
        in: header
        name: X-Service-Id
        required: true
        type: string
      - description: Username associated with the request
        in: header
        name: X-Username
        required: true
        type: string
      - default: id
        description: Language preference for the response
        in: header
        name: Accept-Language
        required: true
        type: string
      - default: 'User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_4_2 like Mac OS
          X'
        description: User agent identifier
        in: header
        name: User-Agent
        required: true
        type: string
      - default: Basic dXNlcm5hbWU6cGFzc3dvcmQ=
        description: Authorization token
        in: header
        name: Authorization
        required: true
        type: string
      - default: 1.2.3
        description: Application version
        in: header
        name: X-App-Version
        type: string
      - description: Withdraw Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/withdraw.WithdrawRequestDto'
      produces:
      - application/json
      responses:
        "200":
          description: Withdrawal Successful
          schema:
            additionalProperties: true
            type: object
      summary: Withdraw funds from wallet
      tags:
      - wallet-controller
swagger: "2.0"
